# -*- coding: utf-8 -*-
"""W6b-2 (assembly) · nine parsed families -> one canonical decision state.

The readers answer "what do the declared sources say". This answers the question
after it: "what is the canonical state of one decision date", which is the thing
`run_decision` actually consumes. A snapshot that has bound and parsed its
sources has still not produced a decision input, and `l3_snapshot` stays
RECEIPT_ONLY until this runs.

WHAT IS ASSEMBLED, AND WHAT IS DELIBERATELY NOT
------------------------------------------------
This builds the MARKET side only:

    as_of · marks · adv20 · sigma20d · execution date and prices · untradable
    SecurityPitInputs · listing spells · PIT status dates · CA events

The portfolio side (cash, shares, pending_exit, receivables, exposures) is NOT
here and is not defaulted. Definition B: `portfolio[t]` is causally generated by
executing t-1, so a market-side state carrying an invented portfolio would be a
fabrication wearing a hash. `build_decision_input` takes the portfolio as an
ARGUMENT — from the checkpoint for t > 1, from the frozen opening state for
t = 1 — and `assert_market_state_is_portfolio_free` pins the separation.

WHERE THE RULES COME FROM
-------------------------
Same line the readers draw, one layer up. Every rule that decides a NUMBER is
imported from a normative module inside the A2 route closure:

    derive_current_spell        core.b0_listing_spell     O-G
    compute_sigma20d            core.b0_state             C-26
    holder_multiplier           core.b0_share_unit_adjustment  C-50/C-51
    series_requirements         core.b0_features          4.1a depths
    SecurityPitInputs           core.b0_features
    resolve_as_of / build_input core.b0_route / adapter   §6.5 / §6.6

What is transcribed is the LAYOUT that has no core function: the ADV20 mean, the
C-50 division of prices before a boundary, 4.1a-R2's calendar-quarter and
calendar-month indexing, and the month-end selection. Those are checked the only
way that means anything — `verify_market_state_parity` rebuilds period 141 and
compares the canonical hash against the sealed one.

⚠ DEPTHS ARE DERIVED, NEVER RESTATED. The first sealed L2 run rejected 100% of
the universe in every period because its builder said 13 where `revenue_accel`
needs 18, and nothing compared the two. `series_requirements()` is read here for
the same reason.

⚠ THE SPANS ARE NOT DECIDED HERE. §19 / C-68 (Master v1.34) registered the
derivation for a prospective decision, and `core.b0_l3_price_span` is its only
producer. This module is ENFORCEMENT: it asks that producer for all four
endpoints and refuses anything else, including a caller-supplied span.

    price_span[0]   the frozen `lineage_price_floor`, captured once at lineage
                    inception. It sets the listing spells, and through them the
                    ADV20/sigma20d gating and the month-end blanking. Measured:
                    L2's own sealed 2026-03 state puts 1,437 of 1,958 spell
                    starts at its panel-span floor of 2013-01-02, which is not
                    where those securities listed.
    price_span[1]   the §6.5 execution session.
    bonus_window    (day after the earliest required month-end price, as_of).

The one thing this module still measures for itself is
`observed_price_coverage_floor` — the depth the declared sources ACTUALLY reach,
before any clipping — because §19.3's three-way disposition can only be evaluated
against it.

⚠ READ-ONLY with respect to `data/b0/`.
"""
from __future__ import annotations

import bisect
import collections
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
for _p in (REPO, HERE, os.path.join(REPO, "research", "b0_materializer")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from core.b0_canonical_hash import canonical_sha256              # noqa: E402
from core.b0_features import (                                   # noqa: E402
    INDUSTRY_UNRESOLVED, SecurityPitInputs, series_requirements,
)
from core.b0_listing_spell import ListingSpell                   # noqa: E402
from core.b0_share_unit_adjustment import (                      # noqa: E402
    ShareUnitAdjustmentError, UnreconstructibleAdjustment,
    assert_kind_classified, holder_multiplier,
)
from core.b0_state import compute_sigma20d                       # noqa: E402
from core import b0_l3_price_span as lsp                         # noqa: E402
from l3_readers import (                                         # noqa: E402
    read_bonus_shares, read_calendar, read_corporate_actions, read_financials,
    read_industry, read_prices, read_revenue, read_security_status,
    read_valuation,
)

ADV_SESSIONS = 20
SIGMA_SESSIONS = 20            # 20 log returns -> 21 closes

_REQ = series_requirements()
QUARTERS = max(8, _REQ["eps_by_quarter"])   # supplied depth may exceed the need
MONTHS_REVENUE = _REQ["monthly_revenue"]    # 18, set by revenue_accel
MONTH_ENDS_REQUIRED = _REQ["month_end_prices"]   # 14, zero margin, intentional

# §19.3: the observed coverage floor must be measured at the SOURCES' depth, not
# at the lineage floor, or the `earlier` disposition can never be seen. A date
# before any market exists is the honest way to say "no lower bound".
SOURCE_DEPTH_PROBE = "0001-01-01"


class AssemblyError(SystemExit):
    """Fail-loud: the declared sources cannot produce a canonical state."""


def _f(v):
    if v is None:
        return None
    try:
        x = float(v)
    except (TypeError, ValueError):
        return None
    return None if x != x or not math.isfinite(x) else x


# --- O-B / O-E-1 · which gaps are explained -------------------------------------

def status_index(status_rows):
    """stock_id -> [(available_from, effective_from, status)], ascending."""
    by = collections.defaultdict(list)
    for r in status_rows:
        by[str(r["stock_id"])].append(
            (r["available_from"] or r["effective_from"],
             r["effective_from"], r["status"]))
    for k in by:
        by[k].sort()
    return by


def known_status_tuple_at(idx, sid, session):
    """B0.6 · O-E-1: the status knowable at `session`, WITH its PIT dates.

    The status string alone was never sufficient: `PitPriceObservation` refuses
    a non-listed status that does not carry the date it became knowable, because
    a suspension filed after the close must not explain that day's missing price.
    Returning only the string is what left the canonical state unable to
    construct the frozen observability object at all — which is why B0.6 exists.

    `available_from` is the semantic dependency; `effective_from` is carried for
    diagnostics only and no rule consults it.
    """
    cur = ("listed", None, None)
    for avail, eff, st in idx.get(sid, ()):
        if str(avail) <= str(session) and str(eff) <= str(session):
            cur = (st, avail, eff)
    return cur


def known_status_at(idx, sid, session):
    return known_status_tuple_at(idx, sid, session)[0]


# --- O-G · listing spells --------------------------------------------------------

def spell_starts(sessions, priced, gap_explained):
    """Ascending spell starts for one security.

    A gap breaks the spell unless something knowable at its FIRST missing
    session explains it (O-G). Computed once over the covered history rather
    than per period: the same rule, evaluated the same way.
    """
    starts, run_start, cur = [], None, None
    for s in sessions:
        if s in priced:
            if cur is None:
                cur = s
                starts.append(s)
            elif run_start is not None and not gap_explained(s_first=run_start):
                cur = s
                starts.append(s)
            run_start = None
        elif cur is not None and run_start is None:
            run_start = s
    return starts


# A SPELL START IS A PROPERTY OF THE CORPUS, NOT OF THE SECURITY.
#
# `spell_starts` opens a spell at the first observed session, so a security
# already listed when the price span begins gets a spell start equal to the span
# floor. That is not an L3 artefact: measured at 2026-03, L2's sealed state says
# 1101 台泥's spell starts 2013-01-02, which is where `build_price_panel.
# panel_span()` starts — January of the year of `window_start` minus
# `lookback_L_months` — not where 台泥 listed.
#
# O-G's `opened_by` admits exactly two values and M-3 aborts on a third, so
# there is no vocabulary for "the corpus starts here". Widening it would be a
# specification change. What this module does instead is REPORT the count, so a
# reader of the receipt can see how many first observations are the span floor
# rather than a listing.
SPELL_FLOOR_SEMANTICS = {
    "field": "spell_starts_at_price_coverage_floor",
    "rule": "A_SPELL_OPENING_AT_THE_SPAN_FLOOR_IS_A_CORPUS_EDGE",
    "measured": (
        "L2's own sealed 2026-03 state puts 1,437 of 1,958 spell starts at its "
        "panel-span floor of 2013-01-02"),
    "detail": (
        "`opened_by` is recorded as 'first_observation' because O-G defines no "
        "third value, and that is what L2 sealed. Two routes reading price "
        "spans of different depth produce different spell starts for the same "
        "security at the same as_of — which is why §19 registers the floor in "
        "the specification and freezes it per lineage, rather than leaving it "
        "to whoever calls this module."),
}

# §19 / C-68 · THE SPAN DERIVATIONS ARE REGISTERED, AND NOT IN THIS FILE.
#
# Until Master v1.34 these were required arguments with no default, because the
# frozen spec derived them only for L2's 141-period panel. §19 registered the
# prospective derivation; `core.b0_l3_price_span` is the sole producer and the
# master preregistration is the semantic authority. What remains here is the
# refusal: no default, no caller-supplied override, no local re-derivation.
SPAN_DERIVATION_AUTHORITY = {
    "master_section": lsp.MASTER_SECTION,
    "ruling": lsp.RULING,
    "producer": "core.b0_l3_price_span",
    "this_module": "ENFORCEMENT_NOT_SEMANTIC_AUTHORITY",
    "endpoints": lsp.ENDPOINT_DERIVATIONS,
}


def _earliest_required_month_end(cal, as_of: str) -> str:
    """The session that ends the oldest month `month_end_prices` reaches.

    The producer fixes WHICH month; only the calendar knows which session ends
    it. A month with no session at all is an abort rather than a shifted window:
    silently sliding to the next month is how a bonus window stops covering the
    reach it exists to cover.
    """
    month = lsp.earliest_required_month_end_month(as_of)
    sessions = [s for s in cal if s[:7] == month]
    if not sessions:
        raise AssemblyError(
            "abort: the declared calendar has no session in %s, the oldest month "
            "the %d-month month-end reach needs from as_of %s (§19.2)"
            % (month, MONTH_ENDS_REQUIRED, as_of))
    return max(sessions)


def price_coverage_floor(px) -> str:
    """The first session the price frame actually covers, from the data."""
    if px.empty:
        raise AssemblyError("abort: the declared price sources yielded no rows")
    return str(px["date"].min())


# §2.8.3 · the two halves, spelled the way the corpus spells them.
# `build_prices_leaf` stamps these strings on every consumed entry and
# `l3_readers.read_prices` dispatches on them. Naming them here rather than
# repeating the literals is what keeps the guard and the leaf from drifting into
# two vocabularies that agree by coincidence.
LEG_PRE_2019 = "pre-2019"
LEG_2019_PLUS = "2019+"


def assert_both_price_legs_are_declared(run_dir: str) -> dict:
    """§2.8.3's lineage has two halves, and a leaf must declare both.

    The actionable form of the floor problem. Measured on the 2026-03 state
    while only the 2019+ leg was declared: 1,706 of 1,958 spell starts MOVED,
    most of them to 2019-01-02 — the corpus edge wearing a listing date.

    ⚠ BOTH ABSENCES ARE NAMED, because only one of them used to be. This guard
    checked the pre-2019 half and let the other fall through to `read_prices`,
    which builds the archive leg out of `frames[1:]` and therefore reached
    `pandas.concat([])`. Reproduced on a leaf carrying the cache leg alone:

        ValueError: No objects to concatenate      l3_readers.py:421

    Same class of absence as the one above, arriving as a library traceback that
    names neither the leaf, nor the leg, nor the run — while the sibling case
    names all three. An operator cannot act on the first message and can act on
    the second, and which one they get was decided by which half went missing.
    """
    from l3_readers import consumed_entries
    from source_ownership_manifest import LEAF_FILENAME, load_leaf

    leaf = load_leaf(os.path.join(run_dir, LEAF_FILENAME % "prices"))
    legs = collections.Counter(e.get("leg") or "unlabelled"
                               for e in consumed_entries(leaf))
    if LEG_PRE_2019 not in legs:
        raise AssemblyError(
            "abort: the prices leaf declares no pre-2019 leg (legs present: "
            "%s). §2.8.3 splits the price lineage at 2019-01-01 and the halves "
            "live in different trees; with only the later half declared, every "
            "listing spell for a security already listed in 2018 opens at the "
            "first covered session." % dict(legs))
    if LEG_2019_PLUS not in legs:
        raise AssemblyError(
            "abort: the prices leaf declares no 2019+ leg (legs present: %s). "
            "§2.8.3 splits the price lineage at 2019-01-01 and the halves live "
            "in different trees; with only the earlier half declared the price "
            "frame stops at 2018-12-31, so the decision date carries no mark, "
            "no ADV20 and no sigma20d for any security, and the §6.5 execution "
            "session has no opening price at all. An entry that carries no "
            "`leg` is not this half: `read_prices` sends every unlabelled entry "
            "down the 2019+ archive path, which is the declaration this leaf "
            "did not make." % dict(legs))
    return dict(legs)


# --- C-50 / C-51 · the adjusted price series ------------------------------------

def adjustment_plan(ledger, bonus_panel, cal):
    """(factors, unresolved_from) per security.

    `factors`   : ascending [(boundary_session, multiplier)] for every eligible
                  event whose holder multiplier is admissible.
    `unresolved`: ASCENDING boundaries of eligible events whose multiplier is
                  not reconstructible. Prices strictly before such a boundary
                  cannot be put on a comparable unit basis, so they are NA
                  (C-50/R8) rather than silently left unadjusted.

                  A LIST rather than a single latest boundary, because the
                  applicable one depends on as_of: an event that has not
                  happened yet cannot have broken a past window, and collapsing
                  the list to its maximum would let a 2026 event blank a 2014
                  momentum. That is look-ahead, and it is the defect this shape
                  exists to avoid.
    """
    bonus = {(str(r.stock_id), str(r.market_effective_session)): r
             for r in bonus_panel.itertuples()}
    calset = set(cal)
    factors = collections.defaultdict(list)
    unresolved = collections.defaultdict(list)
    stats = collections.Counter()
    for row in ledger:
        kind = row["kind"]
        try:
            klass = assert_kind_classified(kind)
        except UnreconstructibleAdjustment:
            stats["kind_unclassified"] += 1
            raise
        if klass != "eligible":
            continue
        sid, ex = str(row["stock_id"]), row["ex_or_effective_date"]
        if not ex:
            continue
        # C-50/R4: a boundary that is not a session resolves forward to the
        # first one, which is that clause's own rule.
        b = ex if ex in calset else next((s for s in cal if s > ex), None)
        if b is None:
            continue
        rec = dict(row)
        if kind == "stock_dividend":
            hit = bonus.get((sid, ex))
            if hit is not None and hit.disposition == "OFFICIAL_BONUS_RATE":
                rec["bonus_shares_per_1000"] = hit.bonus_shares_per_1000
            elif hit is not None and hit.disposition == \
                    "NOT_APPLICABLE_TO_B0_MARKET_HISTORY":
                # C-51/R2: B0 has no market history there to adjust, and this is
                # NOT a missing multiplier. It must not poison later windows.
                stats["not_applicable"] += 1
                continue
        try:
            m = holder_multiplier(rec)
        except ShareUnitAdjustmentError:
            stats["unresolved"] += 1
            unresolved[sid].append(b)
            continue
        stats["resolved_" + kind] += 1
        factors[sid].append((b, float(m)))
    for sid in factors:
        factors[sid].sort()
    for sid in unresolved:
        unresolved[sid].sort()
    return factors, dict(unresolved), stats


def adjusted_closes(dates, closes, factors):
    """C-50/R3: `adjusted = raw / m` for every price BEFORE each boundary."""
    import numpy as np

    if not factors:
        return closes
    out = np.array(closes, dtype=float)
    for boundary, m in factors:
        i = bisect.bisect_left(dates, boundary)
        if i:
            out[:i] /= m
    return out


# --- PIT panels -----------------------------------------------------------------

def financial_index(fin):
    """stock_id -> ascending rows by (release_date, date) (§2.2)."""
    fin = fin.copy()
    fin["release_date"] = fin["release_date"].astype(str).str[:10]
    fin["date"] = fin["date"].astype(str).str[:10]
    fin["stock_id"] = fin["stock_id"].astype(str)
    fin = fin.sort_values(["stock_id", "release_date", "date"])
    by = collections.defaultdict(list)
    for r in fin.itertuples():
        by[r.stock_id].append(r)
    return by


def revenue_index(rev):
    rev = rev.copy()
    rev["release_date"] = rev["release_date"].astype(str).str[:10]
    rev["date"] = rev["date"].astype(str).str[:10]
    rev["stock_id"] = rev["stock_id"].astype(str)
    rev = rev.sort_values(["stock_id", "date"])
    by = collections.defaultdict(list)
    for r in rev.itertuples():
        by[r.stock_id].append((r.release_date, r.date, r.revenue))
    return by


def industry_index(ind):
    by = collections.defaultdict(list)
    for r in ind.itertuples():
        by[str(r.stock_id)].append(
            (str(r.effective_from), str(r.tse_ind_code),
             str(r.unresolved_from) if r.unresolved_from else None))
    for k in by:
        by[k].sort()
    return by


def industry_at(idx, sid, as_of):
    """§2.3 step function; UNRESOLVED from `unresolved_from` onward."""
    code = INDUSTRY_UNRESOLVED
    for eff, tse, unres in idx.get(sid, ()):
        if eff <= as_of:
            code = tse or INDUSTRY_UNRESOLVED
            if unres and unres <= as_of:
                code = INDUSTRY_UNRESOLVED
    return code


# --- per-security precomputation -------------------------------------------------

class SecuritySeries:
    """Everything a period lookup needs, computed once over the covered history.

    Rolling quantities are computed here rather than at lookup time because the
    frozen definitions do not depend on the as-of: C-25's ADV20 is a mean over
    20 OBSERVED sessions and C-26's sigma20d is the SD of 20 log returns, both
    bounded by the current listing spell (O-G).
    """

    __slots__ = ("sid", "dates", "pos", "close", "open_", "adj", "adv20",
                 "sigma20", "month_end", "spells", "unresolved")

    def __init__(self, sid, dates, close, open_, volume, factors,
                 unresolved_from, spells, sigma_at=()):
        self.sid = sid
        self.dates = dates
        self.pos = {d: i for i, d in enumerate(dates)}
        self.close = close
        self.open_ = open_
        self.adj = adjusted_closes(dates, close, factors)
        self.unresolved = tuple(unresolved_from or ())
        self.spells = spells

        self.adv20 = _rolling_mean(close * volume, ADV_SESSIONS)
        self.sigma20 = _rolling_sigma(self.adj, SIGMA_SESSIONS, sigma_at)

        me = {}
        for i, d in enumerate(dates):
            me[d[:7]] = i           # last observed session of each calendar month
        self.month_end = me

    def unresolved_at(self, as_of):
        """C-50/R8 bounded by as_of: the latest broken boundary already in force."""
        i = bisect.bisect_right(self.unresolved, as_of) - 1
        return self.unresolved[i] if i >= 0 else None

    def spell_start(self, as_of):
        i = bisect.bisect_right(self.spells, as_of) - 1
        return self.spells[i] if i >= 0 else None


def _rolling_mean(values, n):
    import numpy as np

    out = np.full(len(values), np.nan)
    if len(values) >= n:
        c = np.cumsum(np.insert(values, 0, 0.0))
        out[n - 1:] = (c[n:] - c[:-n]) / n
    return out


def _rolling_sigma(adj, n, at):
    """C-26 sigma20d, evaluated at the sessions a decision actually stands on.

    `compute_sigma20d` is CALLED rather than reimplemented — a second standard
    deviation in an assembler is exactly the quiet divergence M-1 exists to stop
    — but only at the as-of positions, because the other millions of
    evaluations would be arithmetic nobody reads.
    """
    import numpy as np

    out = np.full(len(adj), np.nan)
    for i in at:
        if i >= n:
            v = compute_sigma20d(list(adj[i - n:i + 1]))
            out[i] = np.nan if v is None else v
    return out


def build_series(px, cal, factors, unresolved, status_idx, as_ofs=()):
    calpos = {d: i for i, d in enumerate(cal)}
    out = {}
    for sid, g in px.groupby("stock_id", sort=True):
        dates = g["date"].tolist()
        close = g["close"].to_numpy(dtype=float)
        open_ = g["open"].to_numpy(dtype=float)
        vol = g["volume_shares"].to_numpy(dtype=float)
        first, last = dates[0], dates[-1]
        expected = cal[calpos[first]: calpos[last] + 1] if first in calpos else dates
        priced = set(dates)

        def explained(s_first, _sid=sid):
            return known_status_at(status_idx, _sid, s_first) != "listed"

        spells = spell_starts(expected, priced,
                              lambda s_first: explained(s_first)) or [dates[0]]
        pos = {d: i for i, d in enumerate(dates)}
        sigma_at = [pos[a] for a in as_ofs if a in pos]
        out[sid] = SecuritySeries(sid, dates, close, open_, vol,
                                  factors.get(sid, ()), unresolved.get(sid, ()),
                                  spells, sigma_at)
    return out


# --- per-period assembly ---------------------------------------------------------

def _quarter_series(rows, as_of, field):
    """The last QUARTERS values of `field`, CALENDAR-QUARTER indexed (4.1a-R2).

    Published on or before as_of (§2.2), then laid out on consecutive fiscal
    quarters with an explicit None for any quarter that has no published figure.
    Compressing the gap out is what makes `series[-5]` stop being four quarters
    before `series[-1]`: measured at L2 period 1, 177 of 1,730 securities
    (10.23%) had a non-contiguous last-8, so eps_growth compared the wrong base
    period and every TTM sum spanned five calendar quarters.
    """
    import pandas as pd

    seen = {}
    for r in rows:
        if r.release_date > as_of:
            continue
        seen[pd.Period(r.date, freq="Q")] = getattr(r, field)
    if not seen:
        return ()
    span = pd.period_range(end=max(seen), periods=QUARTERS, freq="Q")
    return tuple(_f(seen.get(q)) for q in span)


def _latest_quarter_row(rows, as_of):
    best = None
    for r in rows:
        if r.release_date <= as_of and (best is None or (r.date, r.release_date) >
                                        (best.date, best.release_date)):
            best = r
    return best


def _monthly_revenue(rows, as_of):
    """MONTHS_REVENUE values, CALENDAR-MONTH indexed (4.1a-R2).

    `compute_revenue_yoy` reads `series[-1]` against `series[-13]`, so t-12 is
    only truly last year's same month if the index is consecutive months.
    """
    import pandas as pd

    seen = {}
    for rel, d, rev in rows:
        if rel <= as_of:
            seen[pd.Period(d[:7], freq="M")] = rev
    if not seen:
        return []
    span = pd.period_range(end=max(seen), periods=MONTHS_REVENUE, freq="M")
    return [_f(seen.get(m)) for m in span]


def _month_end_prices(ss, as_of, spell, unresolved):
    """14 month-end ADJUSTED closes, newest last. NA where the unit basis breaks."""
    import pandas as pd

    months = pd.period_range(end=pd.Period(as_of[:7], freq="M"),
                             periods=MONTH_ENDS_REQUIRED, freq="M")
    out = []
    for m in months:
        key = str(m)
        i = ss.month_end.get(key)
        if i is None or ss.dates[i] > as_of:
            # the current month is bounded by as_of, not by its calendar end
            cand = [j for j, d in enumerate(ss.dates)
                    if d[:7] == key and d <= as_of]
            i = cand[-1] if cand else None
        if i is None:
            out.append(None)
            continue
        d = ss.dates[i]
        if spell is not None and d < spell:
            out.append(None)              # O-G: a window may not cross a spell
        elif unresolved is not None and d < unresolved:
            out.append(None)              # C-50/R8: no comparable unit basis
        else:
            out.append(_f(ss.adj[i]))
    return out


def build_rows(period, series, fin_idx, rev_idx, ind_idx, val, status_idx,
               ca_by_sid):
    """One row per security quoted at as_of. Same schema as L2's market state."""
    import numpy as np
    import pandas as pd

    as_of, exec_date = period["as_of"], period.get("execution_date")
    window_start = str(pd.Period(as_of[:7], freq="M") - (MONTH_ENDS_REQUIRED - 1))
    rows = []
    for sid, ss in series.items():
        i = ss.pos.get(as_of)
        if i is None:
            continue                       # not quoted at the decision point
        spell = ss.spell_start(as_of)
        if spell is None:
            continue
        n_in_spell = i - ss.pos[spell] + 1
        unres = ss.unresolved_at(as_of)

        adv = ss.adv20[i]
        if n_in_spell < ADV_SESSIONS or not np.isfinite(adv):
            # NA is for a dependency that is genuinely unavailable: fewer than
            # the required observed sessions in this spell (O-G resets ADV20 at
            # the spell start), or a non-finite input.
            adv = None
        # B0.5 · R1/R2: an ADV20 of exactly 0 is NOT encoded as absence. Twenty
        # observed zero-volume sessions average to 0.0, which is a liquidity
        # OBSERVATION — and §4.2 aborts on a MISSING adv20 before it ever
        # reaches the floor that would have rejected the zero anyway.
        sig = ss.sigma20[i]
        if n_in_spell < SIGMA_SESSIONS + 1 or not np.isfinite(sig):
            sig = None
        elif unres is not None and ss.dates[max(0, i - SIGMA_SESSIONS)] < unres:
            sig = None                     # C-50/R8 reaches into the sigma window

        status = known_status_tuple_at(status_idx, sid, as_of)
        j = ss.pos.get(exec_date) if exec_date is not None else None
        v = val.get(sid, {})
        frows = fin_idx.get(sid, ())
        latest = _latest_quarter_row(frows, as_of)
        rows.append({
            "stock_id": sid,
            "mark": _f(ss.close[i]),
            "adv20": _f(adv),
            "sigma20d": _f(sig),
            "execution_open": _f(ss.open_[j]) if j is not None else None,
            "spell_start": spell,
            "known_status": status[0],
            "status_available_from": status[1],
            "status_effective_from": status[2],
            "month_end_prices": _month_end_prices(ss, as_of, spell, unres),
            "monthly_revenue": [_f(x) for x in
                                _monthly_revenue(rev_idx.get(sid, ()), as_of)],
            "net_income_by_quarter": list(_quarter_series(frows, as_of,
                                                          "net_income")),
            "revenue_by_quarter": list(_quarter_series(frows, as_of, "revenue")),
            "gross_profit_by_quarter": list(_quarter_series(frows, as_of,
                                                            "gross_profit")),
            "eps_by_quarter": list(_quarter_series(frows, as_of, "eps")),
            "period_end_equity": _f(getattr(latest, "equity", None)),
            "total_liabilities": _f(getattr(latest, "total_liabilities", None)),
            "total_assets": _f(getattr(latest, "total_assets", None)),
            "current_assets": _f(getattr(latest, "current_assets", None)),
            "current_liabilities": _f(getattr(latest, "current_liabilities", None)),
            "per_tse": _f(v.get("per_tse")),
            "pbr_tse": _f(v.get("pbr_tse")),
            "pit_industry": industry_at(ind_idx, sid, as_of),
            "corporate_action_events": [
                [e["kind"], e["ex_or_effective_date"], e["reconstructibility"]]
                for e in ca_by_sid.get(sid, ())
                if window_start <= e["ex_or_effective_date"] <= as_of],
        })
    return rows


# --- the hashed view -------------------------------------------------------------

PORTFOLIO_FIELDS = ("cash", "shares", "pending_exit", "cash_dividend_receivable",
                    "stock_dividend_receivable", "exposures", "portfolio")


def market_state_payload(period, rows):
    """The market side of `CanonicalDecisionInput.state_payload`, and only that.

    Deliberately absent: cash, shares, pending_exit, receivables and exposures.
    Definition B — those are causally generated by executing the previous
    period, so a market-side hash including a placeholder for them would be a
    hash of a fabrication.
    """
    return {
        "decision_month": period["decision_month"],
        "decision_date": period["decision_date"],
        "as_of": period["as_of"],
        "execution_date": period.get("execution_date"),
        "marks": {r["stock_id"]: r["mark"] for r in rows
                  if r["mark"] is not None and r["mark"] > 0},
        "adv20": {r["stock_id"]: r["adv20"] for r in rows
                  if r["adv20"] is not None},
        "sigma20d": {r["stock_id"]: r["sigma20d"] for r in rows
                     if r["sigma20d"] is not None},
        "execution_prices": {r["stock_id"]: r["execution_open"] for r in rows
                             if r["execution_open"] is not None},
        "untradable": sorted(r["stock_id"] for r in rows
                             if r["known_status"] != "listed"),
        # B0.6: the PIT status dates are decision inputs, so the hashed view
        # must bind them — otherwise two states with different status dates
        # hash identically, which is the sealed-input sufficiency defect (C-55)
        # one field further down. Only non-listed rows carry information here.
        "security_status": [
            {"stock_id": r["stock_id"], "known_status": r["known_status"],
             "status_available_from": r["status_available_from"],
             "status_effective_from": r["status_effective_from"]}
            for r in sorted(rows, key=lambda x: x["stock_id"])
            if r["known_status"] != "listed"],
        "listing_spells": [{"stock_id": r["stock_id"], "start": r["spell_start"]}
                           for r in sorted(rows, key=lambda x: x["stock_id"])],
        "pit_inputs": [
            {"stock_id": r["stock_id"],
             "net_income_by_quarter": r["net_income_by_quarter"],
             "revenue_by_quarter": r["revenue_by_quarter"],
             "gross_profit_by_quarter": r["gross_profit_by_quarter"],
             "eps_by_quarter": r["eps_by_quarter"],
             "period_end_equity": r["period_end_equity"],
             "total_liabilities": r["total_liabilities"],
             "total_assets": r["total_assets"],
             "current_assets": r["current_assets"],
             "current_liabilities": r["current_liabilities"],
             "monthly_revenue": r["monthly_revenue"],
             "month_end_prices": r["month_end_prices"],
             "per_tse": r["per_tse"],
             "pbr_tse": r["pbr_tse"],
             "pit_industry": r["pit_industry"]}
            for r in sorted(rows, key=lambda x: x["stock_id"])],
        "corporate_action_events": [
            {"stock_id": r["stock_id"], "events": r["corporate_action_events"]}
            for r in sorted(rows, key=lambda x: x["stock_id"])
            if r["corporate_action_events"]],
    }


def decision_cutoff_payload(period, rows):
    """Canonical market facts knowable at ``as_of`` in either phase.

    The executable assembly necessarily contains the following session's open
    and names that session in ``execution_date``.  Those facts did not exist at
    the decision cut-off and therefore cannot be part of the identity handed
    from an intent run to its later execution.  Everything else is kept byte
    for byte identical to :func:`market_state_payload`.
    """
    cutoff_period = dict(period)
    cutoff_period["execution_date"] = None
    cutoff_rows = [dict(row, execution_open=None) for row in rows]
    return market_state_payload(cutoff_period, cutoff_rows)


def assert_market_state_is_portfolio_free(payload):
    """Definition B, as a check rather than a comment."""
    leaked = [k for k in PORTFOLIO_FIELDS if k in payload]
    if leaked:
        raise AssemblyError(
            "abort: the market-side state carries portfolio field(s) %s. "
            "portfolio[t] is causally generated by executing t-1 and may not be "
            "invented here." % leaked)


# --- the entry point -------------------------------------------------------------

def assemble(run_dir: str, run_id: str, decision_date: str,
             lineage_price_floor=None) -> dict:
    """Declared sources -> the market side of one canonical decision state.

    `lineage_price_floor` is the ONE frozen input §19 leaves to the lineage, and
    it still has no default here: a floor invented at call time would move
    `spell_start` and the state hash without anybody having ruled on it. Every
    other endpoint is derived by `core.b0_l3_price_span` from `as_of` and the
    §6.5 execution session, and this module may not override any of them.
    """
    return _assemble(run_dir, run_id, decision_date, lineage_price_floor,
                     decision_intent_only=False)


def assemble_decision_intent(run_dir: str, run_id: str, decision_date: str,
                             lineage_price_floor=None) -> dict:
    """Materialize only facts knowable at the decision cut-off.

    The source span ends at ``as_of`` because the next execution session has
    not happened.  No execution date or opening price is guessed or admitted.
    This object may feed ``build_decision_intent`` but not ``run_decision``.
    """
    return _assemble(run_dir, run_id, decision_date, lineage_price_floor,
                     decision_intent_only=True)


def _assemble(run_dir: str, run_id: str, decision_date: str,
              lineage_price_floor, *, decision_intent_only: bool) -> dict:
    from l3_snapshot import plan, plan_decision_intent

    planner = plan_decision_intent if decision_intent_only else plan
    period = dict(planner(run_dir, run_id, decision_date))
    # The month a decision belongs to is the month of its DECISION DATE, not of
    # its as_of. They differ whenever §6.6 resolves back across a month boundary,
    # and labelling the state by as_of would file a 2026-04-30 decision under
    # 2026-04 in one run and 2026-05 in another.
    period["decision_month"] = period["decision_date"][:7]
    as_of, exec_date = period["as_of"], period.get("execution_date")
    if lineage_price_floor is None:
        raise AssemblyError(
            "abort: this run declares no `lineage_price_floor`, and one may not "
            "be chosen here (§19 / C-68).\n"
            "The floor is captured ONCE at lineage inception, from a complete, "
            "hash-bound price leaf with the D-1 quarantine applied, and is then "
            "a constant of that lineage. It sets the listing spells — and "
            "through them the ADV20 / sigma20d gating and the month-end "
            "blanking — so a floor picked at call time is a state-hash decision "
            "nobody ruled on. See `core.b0_l3_price_span.capture_lineage_floor`.")

    legs = assert_both_price_legs_are_declared(run_dir)
    cal = list(read_calendar(run_dir))
    try:
        # The executable route binds through the observed execution session.
        # A decision intent cannot: its admissible price endpoint is the
        # completed decision cut-off, and the missing execution fact remains
        # explicit in ``period["execution_date"]``.
        price_endpoint = as_of if decision_intent_only else exec_date
        price_span = lsp.price_span(lineage_price_floor, price_endpoint)
        bonus_window = lsp.bonus_window(as_of, _earliest_required_month_end(cal, as_of))
    except lsp.L3SpanError as exc:
        raise AssemblyError(str(exc))

    status = read_security_status(run_dir)
    ledger = read_corporate_actions(run_dir, status_rows=status)
    bonus = read_bonus_shares(run_dir, bonus_window[0], bonus_window[1],
                              ledger=ledger, sessions=cal)
    # Read from the sources' own depth first: §19.3's disposition is a statement
    # about what the DECLARED SOURCES reach, and a frame already clipped to the
    # lineage floor can no longer answer it — `earlier` would be indistinguishable
    # from `equal`, which is precisely the drift this rule exists to catch.
    px = read_prices(run_dir, SOURCE_DEPTH_PROBE, price_span[1])
    px = px.sort_values(["stock_id", "date"]).reset_index(drop=True)
    observed_floor = price_coverage_floor(px)
    try:
        disposition = lsp.assert_floor_conforms(price_span[0], observed_floor)
    except lsp.L3SpanError as exc:
        raise AssemblyError(str(exc))
    px = px[px["date"] >= price_span[0]].reset_index(drop=True)
    if px.empty:
        raise AssemblyError(
            "abort: no price rows at or after the lineage floor %s" % price_span[0])
    floor = price_coverage_floor(px)

    factors, unresolved, adj_stats = adjustment_plan(ledger, bonus, cal)
    status_idx = status_index(status)
    series = build_series(px, cal, factors, unresolved, status_idx, [as_of])

    fin_idx = financial_index(read_financials(run_dir))
    rev_idx = revenue_index(read_revenue(run_dir))
    ind_idx = industry_index(read_industry(run_dir))
    val = read_valuation(run_dir)
    ca_by_sid = collections.defaultdict(list)
    for row in ledger:
        ca_by_sid[str(row["stock_id"])].append(row)

    rows = build_rows(period, series, fin_idx, rev_idx, ind_idx, val,
                      status_idx, ca_by_sid)
    if not rows:
        raise AssemblyError(
            "abort: %s produced no market-side state" % period["decision_month"])

    payload = market_state_payload(period, rows)
    cutoff_payload = decision_cutoff_payload(period, rows)
    assert_market_state_is_portfolio_free(payload)
    assert_market_state_is_portfolio_free(cutoff_payload)
    return {
        "period": period,
        "rows": rows,
        "payload": payload,
        "market_state_sha256": canonical_sha256(payload),
        "decision_cutoff_state_sha256": canonical_sha256(cutoff_payload),
        "share_unit_adjustment": dict(adj_stats),
        "securities": len(rows),
        "bonus_window": list(bonus_window),
        "price_span": list(price_span),
        "span_derivation_authority": SPAN_DERIVATION_AUTHORITY,
        # §19.4: BOTH floors travel together. The frozen one says what the
        # lineage promised; the observed one says what the sources actually
        # reach. Either alone is unauditable.
        "lineage_price_floor": str(lineage_price_floor),
        "observed_price_coverage_floor": observed_floor,
        "floor_disposition": disposition,
        "price_legs": legs,
        "price_coverage_floor": floor,
        # See SPELL_FLOOR_SEMANTICS: how many first observations are the corpus
        # starting rather than the security listing.
        "spell_starts_at_price_coverage_floor": sum(
            1 for r in rows if str(r["spell_start"]) <= floor),
        "spell_floor_semantics": SPELL_FLOOR_SEMANTICS,
        "decision_layer_invoked": False,
        "performance_computed": False,
        "decision_intent_only": bool(decision_intent_only),
        "price_span_endpoint_kind": (
            "AS_OF_DECISION_CUTOFF" if decision_intent_only
            else "OBSERVED_EXECUTION_SESSION"),
    }


def build_production_sources(assembled: dict, run_dir: str, attestation):
    """The market half of `ProductionSources`. No portfolio, by construction."""
    from core.b0_adapter_production import ProductionSources
    from core.b0_market_state import (
        SecurityStatusTable, SourceContract, StatusRecord, TradingCalendar,
    )

    as_of = assembled["period"]["as_of"]
    rows = assembled["rows"]
    # The FULL declared series, not a slice ending at as_of. `TradingCalendar`
    # exists to hold it safely: it exposes only `sessions_through(as_of)`,
    # because handing out the whole sequence would let a caller ask "is next
    # month a holiday?" — answerable in reality, not from data a replay may
    # hold. Truncating here would also leave §6.5's execution session outside
    # the calendar that is supposed to contain it.
    sessions = tuple(read_calendar(run_dir))
    # The same asymmetry as the price legs, one family over: the status table
    # below names its own emptiness and this one did not. `SourceContract` takes
    # `date_min=sessions[0]` and `date_max=sessions[-1]`, so a calendar leaf that
    # parsed to nothing arrived as `IndexError: tuple index out of range` from a
    # dataclass constructor — naming neither the family nor the run.
    if not sessions:
        raise AssemblyError(
            "abort: the declared calendar leaf yielded no sessions. An empty "
            "calendar and a calendar nobody built are not the same fact, and "
            "the difference decides §6.5's execution session, every spell "
            "boundary and the month-end reach.")

    calendar = TradingCalendar(
        sessions=sessions,
        source=SourceContract(
            name="l3_trading_calendar", kind="trading_calendar",
            importer_version="l3_calendar_reader@1",
            content_sha256=canonical_sha256(list(sessions)),
            schema_sha256=canonical_sha256(["session"]),
            date_min=sessions[0], date_max=sessions[-1],
            has_effective_dates=True,        # each session IS its own effective date
            has_availability_semantics=True,  # a traded session is known that day
            is_current_snapshot=False,
            availability_convention=(
                "observed sessions only; a session is knowable on the day it "
                "trades. A forward-published holiday schedule is not used, "
                "because it would let a replay standing at t assert facts about "
                "sessions after t.")))

    # O-E-1, applied where the table is built rather than where it is read: a
    # record filed after as_of is not knowable at as_of, and one that has not
    # taken effect yet explains nothing.
    status_rows = [r for r in read_security_status(run_dir)
                   if r["available_from"] <= as_of and
                   r["effective_from"] <= as_of]
    if not status_rows:
        raise AssemblyError(
            "abort: no status record is knowable at %s. An empty status table "
            "and a table nobody built are not the same fact, and the "
            "difference decides whether a price gap can be explained." % as_of)
    status_table = SecurityStatusTable(
        [StatusRecord(**{k: r[k] for k in
                         ("stock_id", "status", "effective_from",
                          "available_from", "reason", "source")})
         for r in status_rows],
        SourceContract(
            name="l3_security_status", kind="security_status",
            importer_version="l3_status_reader@1",
            content_sha256=canonical_sha256(status_rows),
            schema_sha256=canonical_sha256(
                ["stock_id", "status", "effective_from", "available_from",
                 "reason", "source"]),
            date_min=min(r["effective_from"] for r in status_rows),
            date_max=max(r["effective_from"] for r in status_rows),
            has_effective_dates=True, has_availability_semantics=True,
            is_current_snapshot=False,
            availability_convention=(
                "available_from = 年月日 (first affected session). O-E-1 then "
                "lets a record explain only sessions STRICTLY AFTER it, so a "
                "status filed after the close can never account for that day's "
                "missing price.")))

    marks, adv20, sigma20d, exec_px, untradable = {}, {}, {}, {}, set()
    pit_inputs, spells = [], []
    for r in rows:
        sid = r["stock_id"]
        if r["mark"] is not None and r["mark"] > 0:
            marks[sid] = r["mark"]
        if r["adv20"] is not None:
            adv20[sid] = r["adv20"]
        if r["sigma20d"] is not None:
            sigma20d[sid] = r["sigma20d"]
        if r["execution_open"] is not None:
            exec_px[sid] = r["execution_open"]
        if r["known_status"] != "listed":
            untradable.add(sid)
        # O-G defines two values and no third; `first_observation` is what L2
        # seals here too. SPELL_FLOOR_SEMANTICS records how many of these are
        # the corpus edge rather than a listing.
        spells.append(ListingSpell(stock_id=sid, start=str(r["spell_start"]),
                                   opened_by="first_observation", as_of=as_of))
        pit_inputs.append(SecurityPitInputs(
            stock_id=sid,
            net_income_by_quarter=tuple(r["net_income_by_quarter"]),
            revenue_by_quarter=tuple(r["revenue_by_quarter"]),
            gross_profit_by_quarter=tuple(r["gross_profit_by_quarter"]),
            eps_by_quarter=tuple(r["eps_by_quarter"]),
            period_end_equity=r["period_end_equity"],
            total_liabilities=r["total_liabilities"],
            total_assets=r["total_assets"],
            current_assets=r["current_assets"],
            current_liabilities=r["current_liabilities"],
            monthly_revenue=tuple(r["monthly_revenue"]),
            month_end_prices=tuple(r["month_end_prices"]),
            per_tse=r["per_tse"], pbr_tse=r["pbr_tse"],
            pit_industry=str(r["pit_industry"])))

    # ⚠ `price_observations` and `corporate_action_events` are EMPTY here, and
    # that is definition A, not an oversight. Both are consumed per HELD
    # position — `assert_no_unexplained_gap_in_holdings` asks whether a gap in
    # something B0 owns is explained, and B0.4's reconstruction block fires on
    # held + exit + NOT_RECONSTRUCTIBLE. With no portfolio there is nothing to
    # ask about, so they belong to the portfolio side and the runner (B7) fills
    # them once the checkpoint supplies `portfolio[t]`. Populating them from the
    # whole universe here would not be more complete; it would be a different
    # object answering a question nobody asked.
    return ProductionSources(
        calendar=calendar, status_table=status_table, attestation=attestation,
        marks=marks, adv20=adv20, sigma20d=sigma20d,
        pit_inputs=tuple(pit_inputs), price_observations=(),
        corporate_action_events=(), exposures=(),
        listing_spells=tuple(spells)), exec_px, frozenset(untradable)


def build_decision_input(assembled: dict, sources, portfolio, execution_prices,
                         untradable):
    """The full input. `portfolio` is an ARGUMENT — definition B, not a default."""
    from core.b0_adapter_production import build_input

    p = assembled["period"]
    return build_input(sources, portfolio, p["decision_date"],
                       p["execution_date"], execution_prices, untradable)


def build_decision_intent_input(assembled: dict, sources, portfolio):
    """Build the canonical decision-time input without execution facts."""
    from core.b0_adapter_production import build_intent_input

    p = assembled["period"]
    if p.get("execution_date") is not None:
        raise AssemblyError(
            "abort: decision-intent input unexpectedly carries an execution "
            "date; use build_decision_input for an executable period.")
    return build_intent_input(sources, portfolio, p["decision_date"])
