"""C-53 · the opening-state seam, frozen as a boundary rule.

Two dates describe the same moment and are not the same date:

    registered opening state   `window_start` — the DECISION date the registry
                               declares B0 starts the window on (2014-07-31)
    canonical decision input   `resolve_as_of(window_start)` — the prior
                               completed session §6.6 dates decision state at
                               (2014-07-30)

With no holdings the two describe the same economic state, and they hash
differently. Materializing period 1 forced the question: the retrospective
adapter refuses to re-date a portfolio ("the adapter does not re-date a
portfolio; it reports the mismatch"), and rightly — a portfolio silently moved
onto a different session is a portfolio asserting it was worth something on a day
it was not observed.

The ruling is a BOUNDARY rule, not a mechanism. Period 1's opening state — and
only period 1's — is normalized onto the canonical as-of session, and both hashes
are bound so that neither identity is lost. Every other period's portfolio is an
execution output whose date is a fact about when it was produced, and
`assert_opening_state_normalization` refuses to touch one.

What makes the normalization safe is checkable rather than asserted: every
portfolio-economic field must be identical across the two datings, and the ONLY
permitted difference is the date metadata itself. If a future opening state ever
carries holdings, cash-in-transit or a receivable, this check fails and the
normalization stops — which is the point.
"""

from __future__ import annotations

from typing import Mapping

# The two datings, named so that "which one is this hash" is answerable.
REGISTERED_OPENING_STATE_DATE = "window_start"
CANONICAL_OPENING_STATE_DATE = "resolve_as_of(window_start)"

# R2: a boundary rule. Not a generic re-dating facility, and the scope is part of
# the specification rather than a convention in the caller.
NORMALIZATION_SCOPE = "period_1_opening_state_only"
NORMALIZATION_PERIOD_INDEX = 1

# Everything that says what the portfolio IS. All of it must survive the
# normalization unchanged.
PORTFOLIO_ECONOMIC_FIELDS: tuple[str, ...] = (
    "cash",
    "shares",
    "pending_exit",
    "cash_dividend_receivable",
    "stock_dividend_receivable",
)

# The only fields the normalization is permitted to move.
PERMITTED_DATE_METADATA_FIELDS: tuple[str, ...] = ("as_of",)


class OpeningStateError(RuntimeError):
    """Fail-loud: a re-dating the boundary rule does not authorise."""


def registered_opening_state(window_start: str, c_ref: float) -> dict:
    """The opening state as the registry declares it. Read, never invented."""
    return {
        "as_of": str(window_start),
        "cash": float(c_ref),
        "shares": {},
        "pending_exit": {},
        "cash_dividend_receivable": 0.0,
        "stock_dividend_receivable": {},
    }


def canonical_opening_state(registered: Mapping[str, object],
                            as_of: str) -> dict:
    """The same economic state, dated at the canonical decision session."""
    out = dict(registered)
    out["as_of"] = str(as_of)
    return out


def assert_opening_state_normalization(registered: Mapping[str, object],
                                       canonical: Mapping[str, object],
                                       *, period_index: int) -> None:
    """R2, as an executable invariant.

    Three things have to hold, and each of them is a way the rule could be
    abused if it did not:

      1. This is period 1. Any other period's portfolio is an execution output.
      2. Only `as_of` differs, and it differs in the declared direction —
         canonical strictly before registered, because §6.6 dates decision state
         at the PRIOR completed session.
      3. Every portfolio-economic field is identical. Not "equivalent", not
         "within tolerance" — identical.
    """
    if period_index != NORMALIZATION_PERIOD_INDEX:
        raise OpeningStateError(
            f"C-53/R2: the opening-state normalization is "
            f"{NORMALIZATION_SCOPE}; period {period_index} was requested. A "
            f"later period's portfolio is generated by executing the period "
            f"before it, and its date is a fact about when it was produced.")

    reg_keys, can_keys = set(registered), set(canonical)
    if reg_keys != can_keys:
        raise OpeningStateError(
            f"C-53/R2: the two datings do not describe the same object; keys "
            f"differ by {reg_keys ^ can_keys}. A normalization that adds or "
            f"drops a field is not a re-dating.")

    differing = [k for k in sorted(reg_keys) if registered[k] != canonical[k]]
    unexpected = [k for k in differing if k not in PERMITTED_DATE_METADATA_FIELDS]
    if unexpected:
        raise OpeningStateError(
            f"C-53/R2: normalizing the opening state changed {unexpected}. Only "
            f"{list(PERMITTED_DATE_METADATA_FIELDS)} may move; every "
            f"portfolio-economic field must be identical across the two "
            f"datings.")

    for field in PORTFOLIO_ECONOMIC_FIELDS:
        if field not in registered:
            raise OpeningStateError(
                f"C-53/R2: the opening state does not declare {field!r}. An "
                f"absent economic field cannot be shown to have survived the "
                f"normalization.")
        if registered[field] != canonical[field]:
            raise OpeningStateError(
                f"C-53/R2: {field!r} differs across the two datings "
                f"({registered[field]!r} vs {canonical[field]!r}). The "
                f"normalization moves a date, never an economic quantity.")

    if not str(canonical["as_of"]) < str(registered["as_of"]):
        raise OpeningStateError(
            f"C-53/R2: the canonical as-of {canonical['as_of']!r} is not "
            f"strictly before the registered opening date "
            f"{registered['as_of']!r}. §6.6 dates decision state at the prior "
            f"completed session; any other direction is a different rule.")


def assert_not_a_generic_redater(portfolio_as_of: str,
                                 target_as_of: str,
                                 *, is_opening_state: bool) -> None:
    """R2's last clause: no path may re-date an arbitrary portfolio.

    Called by anything tempted to reconcile a portfolio date mismatch. Only the
    opening state has a second admissible dating; everything else must report
    the mismatch, which is what the adapter already does.
    """
    if str(portfolio_as_of) == str(target_as_of):
        return
    if not is_opening_state:
        raise OpeningStateError(
            f"C-53/R2: a portfolio dated {portfolio_as_of} may not be moved to "
            f"{target_as_of}. The opening state is the only portfolio with two "
            f"admissible datings; every other one is an execution output, and "
            f"re-dating it would assert a position on a session it was never "
            f"observed on.")
