# -*- coding: utf-8 -*-
"""Materialize the 141 market-side canonical states. READ-ONLY, pre-L2.

Definition A: every one of the 141 frozen decision periods must be buildable,
deterministic and hashable from sealed sources alone. This builder produces the
MARKET side of `CanonicalDecisionInput` — everything a period's state contains
that does not depend on what B0 held:

    as_of · marks · adv20 · sigma20d · execution date and prices · untradable
    SecurityPitInputs (financials, monthly revenue, valuation, industry,
    month-end prices) · price observations · corporate-action events ·
    listing spells · source attestation

The portfolio side (cash, shares, pending_exit, receivables, exposures) is NOT
here and is not defaulted to anything. Definition B: `portfolio[t]` is causally
generated by executing t-1, so a market-side state that carried an invented
portfolio would be a fabrication wearing a hash. `build_period_1_full_input`
below is the only place a full `CanonicalDecisionInput` is constructed, and it
consumes the sealed opening portfolio rather than a default.

No decision, ranking, portfolio, NAV or performance quantity is computed, and
`run_decision` is never called.

    python research/b0_materializer/build_market_side_state.py
"""
from __future__ import annotations

import bisect
import collections
import csv
import json
import math
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, REPO)

from core.b0_canonical_hash import canonical_sha256          # noqa: E402
from core.b0_features import INDUSTRY_UNRESOLVED             # noqa: E402
from core.b0_master_prereg import (                          # noqa: E402
    FROZEN_B0_LINEAGE, lineage_spec, spec as frozen_spec,
)
from core.b0_share_unit_adjustment import (                  # noqa: E402
    ELIGIBLE_KINDS, ShareUnitAdjustmentError, UnreconstructibleAdjustment,
    assert_kind_classified, holder_multiplier,
)
from core.b0_state import compute_sigma20d                   # noqa: E402

# --- lineage scoping ---------------------------------------------------------
# Which lineage is being materialized. Frozen B0 remains the default so that
# every existing caller, receipt and test keeps its exact behaviour; a second
# lineage must ASK for itself, because a silent fallback to B0 is precisely how
# a B1 build would overwrite B0's 141 sealed states while every assertion below
# still passed.
LINEAGE = os.environ.get("B0_MATERIALIZE_LINEAGE", FROZEN_B0_LINEAGE)

# Frozen B0 keeps `data/b0/...` byte-for-byte. Anything else gets its own root.
DATA = os.path.join(REPO, "data", "b0" if LINEAGE == FROZEN_B0_LINEAGE
                    else LINEAGE.lower())
OUTDIR = os.path.join(DATA, "market_state")
MANIFEST = os.path.join(DATA, "market_state_manifest.json")
RECEIPT = os.path.join(
    HERE, "market_side_state_receipt.json" if LINEAGE == FROZEN_B0_LINEAGE
    else "market_side_state_receipt_%s.json" % LINEAGE.lower())

FROZEN_B0_STATE_DIR = os.path.join(REPO, "data", "b0", "market_state")


def assert_not_writing_into_frozen_b0(path: str) -> None:
    """A NON-B0 lineage may not write anywhere under data/b0/market_state.

    This is a guard, not a convention. Frozen B0's 141 market-side state hashes
    are its sealed identity; the run that would destroy them is not a malicious
    one, it is an ordinary `python build_market_side_state.py` with the wrong
    environment variable set. The check is on the resolved absolute path so that
    a relative path, a symlink or a `..` cannot walk into it.
    """
    if LINEAGE == FROZEN_B0_LINEAGE:
        return
    target = os.path.realpath(path)
    protected = os.path.realpath(FROZEN_B0_STATE_DIR)
    if target == protected or target.startswith(protected + os.sep):
        raise SystemExit(
            "REFUSING TO WRITE: lineage %s resolved an output path inside "
            "Frozen B0's sealed state directory (%s). B0's 141 state hashes are "
            "its identity and this build would rewrite them." % (LINEAGE, target))

# B-09 / §2.1. Read, never restated: a frozen parameter written out a
# second time is a second source of truth, and it agrees right up until the
# day it does not — the C-55 shape. `spec()` has no default, so a window
# that ever stops being specified aborts here instead of resolving to a
# literal someone typed while the window was a different length.
# Read, never restated - and now read FOR A NAMED LINEAGE. `lineage_spec`
# delegates to `frozen_spec` when the lineage is Frozen B0, so B0's three
# numbers still have exactly one home.
WINDOW_START = lineage_spec(LINEAGE, "window_start")
WINDOW_END = lineage_spec(LINEAGE, "window_end")
WINDOW_MONTHS = lineage_spec(LINEAGE, "window_months")
ADV_SESSIONS = 20
SIGMA_SESSIONS = 20            # 20 log returns -> 21 closes


def _log(msg):
    print(msg, flush=True)


# --- sealed inputs -------------------------------------------------------------

def load_sources():
    cal = sorted(r["session"] for r in csv.DictReader(
        open(os.path.join(DATA, "trading_calendar.csv"), encoding="utf-8")))
    px = pd.read_parquet(os.path.join(DATA, "price_panel.parquet"))
    px["date"] = px["date"].astype(str).str[:10]
    px["stock_id"] = px["stock_id"].astype(str)
    px = px.sort_values(["stock_id", "date"]).reset_index(drop=True)
    ledger = list(csv.DictReader(
        open(os.path.join(DATA, "corporate_actions_ledger.csv"), encoding="utf-8")))
    status = list(csv.DictReader(
        open(os.path.join(DATA, "security_status.csv"), encoding="utf-8")))
    bonus = pd.read_parquet(os.path.join(DATA, "bonus_share_panel.parquet"))
    val = pd.read_parquet(os.path.join(DATA, "valuation_panel.parquet"))
    fin = pd.read_parquet(os.path.join(DATA, "financials_pit.parquet"))
    rev = pd.read_parquet(os.path.join(DATA, "monthly_revenue_pit.parquet"))
    ind = pd.read_parquet(os.path.join(DATA, "industry_pit.parquet"))
    return cal, px, ledger, status, bonus, val, fin, rev, ind


def decision_periods(cal):
    """The 141 frozen decision months and their §6.6 as-of sessions."""
    months = pd.period_range(WINDOW_START[:7], WINDOW_END[:7], freq="M")
    if len(months) != WINDOW_MONTHS:
        raise SystemExit("the frozen window is %d months, got %d"
                         % (WINDOW_MONTHS, len(months)))
    out = []
    for m in months:
        dd = str(m.end_time.date())
        i = bisect.bisect_left(cal, dd)
        prior = [s for s in cal[max(0, i - 10):i] if s < dd]
        if not prior:
            raise SystemExit("§6.6: no completed session before %s" % dd)
        as_of = prior[-1]
        j = bisect.bisect_right(cal, dd)
        if j >= len(cal):
            raise SystemExit("§6.5: no execution session after %s" % dd)
        out.append({"decision_month": str(m), "decision_date": dd,
                    "as_of": as_of, "execution_date": cal[j]})
    return out


# --- O-B / O-E-1 · which gaps are explained -----------------------------------

def status_index(status_rows):
    """stock_id -> [(available_from, effective_from, status)], ascending."""
    by = collections.defaultdict(list)
    for r in status_rows:
        by[str(r["stock_id"])].append(
            (r["available_from"] or r["effective_from"],
             r["effective_from"], r["status"]))
    for k in by:
        by[k].sort()
    return by


def known_status_tuple_at(idx, sid, session):
    """B0.6 · O-E-1: the status knowable at `session`, WITH its PIT dates.

    The status string alone was never sufficient: `PitPriceObservation` refuses a
    non-listed status that does not carry the date it became knowable, because a
    suspension filed after the close must not explain that day's missing price.
    Returning only the string is what left the canonical state unable to
    construct the frozen observability object at all.

    `available_from` is the semantic dependency. `effective_from` is carried for
    diagnostics only and no rule consults it.
    """
    cur = ("listed", None, None)
    for avail, eff, st in idx.get(sid, ()):
        if str(avail) <= str(session) and str(eff) <= str(session):
            cur = (st, avail, eff)
    return cur


def known_status_at(idx, sid, session):
    """The status string alone, for callers that genuinely need only that."""
    return known_status_tuple_at(idx, sid, session)[0]


# --- O-G · listing spells, derived once over the whole history ----------------

def spell_starts(sessions, priced, gap_explained):
    """Ascending spell starts for one security.

    A gap breaks the spell unless something knowable at its FIRST missing
    session explains it (O-G). Computed once over full history rather than
    per period, which is the same rule evaluated the same way.
    """
    starts, run_start, cur = [], None, None
    pset = priced
    for s in sessions:
        if s in pset:
            if cur is None:
                cur = s
                starts.append(s)
            elif run_start is not None and not gap_explained(s_first=run_start):
                cur = s
                starts.append(s)
            run_start = None
        elif cur is not None and run_start is None:
            run_start = s
    return starts


# --- C-50 / C-51 · the adjusted price series ----------------------------------

def adjustment_plan(ledger, bonus_panel, cal):
    """(factors, unresolved_from) per security.

    `factors`  : ascending [(boundary_session, multiplier)] for every eligible
                 event whose holder multiplier is admissible.
    `unresolved`: ASCENDING boundaries of eligible events whose multiplier is not
                 reconstructible. Prices strictly before such a boundary cannot
                 be put on a comparable unit basis, so they are NA (C-50/R8)
                 rather than silently left unadjusted.

                 A LIST rather than a single latest boundary, because the
                 applicable one depends on as_of: an event that has not happened
                 yet cannot have broken a past window, and collapsing the list to
                 its maximum would let a 2026 event blank a 2014 momentum. That
                 is look-ahead, and it is the defect this shape exists to avoid.
    """
    bonus = {(str(r.stock_id), str(r.market_effective_session)): r
             for r in bonus_panel.itertuples()}
    calset = set(cal)
    factors = collections.defaultdict(list)
    unresolved = collections.defaultdict(list)
    stats = collections.Counter()
    for row in ledger:
        kind = row["kind"]
        try:
            klass = assert_kind_classified(kind)
        except UnreconstructibleAdjustment:
            stats["kind_unclassified"] += 1
            raise
        if klass != "eligible":
            continue
        sid, ex = str(row["stock_id"]), row["ex_or_effective_date"]
        if not ex:
            continue
        # R4: the market-effective session. A boundary that is not a session
        # resolves forward to the first one, which is C-50/R4's own rule.
        b = ex if ex in calset else next((s for s in cal if s > ex), None)
        if b is None:
            continue
        rec = dict(row)
        if kind == "stock_dividend":
            hit = bonus.get((sid, ex))
            if hit is not None and hit.disposition == "OFFICIAL_BONUS_RATE":
                rec["bonus_shares_per_1000"] = hit.bonus_shares_per_1000
            elif hit is not None and hit.disposition == \
                    "NOT_APPLICABLE_TO_B0_MARKET_HISTORY":
                # C-51/R2: B0 has no market history there to adjust, and this is
                # NOT a missing multiplier. It must not poison later windows.
                stats["not_applicable"] += 1
                continue
        try:
            m = holder_multiplier(rec)
        except ShareUnitAdjustmentError:
            stats["unresolved"] += 1
            unresolved[sid].append(b)
            continue
        stats["resolved_" + kind] += 1
        factors[sid].append((b, float(m)))
    for sid in factors:
        factors[sid].sort()
    for sid in unresolved:
        unresolved[sid].sort()
    return factors, dict(unresolved), stats


def adjusted_closes(dates, closes, factors):
    """C-50/R3: `adjusted = raw / m` for every price BEFORE each boundary."""
    if not factors:
        return closes
    out = np.array(closes, dtype=float)
    for boundary, m in factors:
        i = bisect.bisect_left(dates, boundary)
        if i:
            out[:i] /= m
    return out


# --- PIT panels ----------------------------------------------------------------

def financial_index(fin):
    """stock_id -> ascending [(release_date, quarter_key, row)] (§2.2)."""
    fin = fin.copy()
    fin["release_date"] = fin["release_date"].astype(str).str[:10]
    fin["date"] = fin["date"].astype(str).str[:10]
    fin["stock_id"] = fin["stock_id"].astype(str)
    fin = fin.sort_values(["stock_id", "release_date", "date"])
    by = collections.defaultdict(list)
    for r in fin.itertuples():
        by[r.stock_id].append(r)
    return by


def revenue_index(rev):
    rev = rev.copy()
    rev["release_date"] = rev["release_date"].astype(str).str[:10]
    rev["date"] = rev["date"].astype(str).str[:10]
    rev["stock_id"] = rev["stock_id"].astype(str)
    rev = rev.sort_values(["stock_id", "date"])
    by = collections.defaultdict(list)
    for r in rev.itertuples():
        by[r.stock_id].append((r.release_date, r.date, r.revenue))
    return by


def industry_index(ind):
    by = collections.defaultdict(list)
    for r in ind.itertuples():
        by[str(r.stock_id)].append(
            (str(r.effective_from), str(r.tse_ind_code),
             str(r.unresolved_from) if r.unresolved_from else None))
    for k in by:
        by[k].sort()
    return by


def industry_at(idx, sid, as_of):
    """§2.3 step function; UNRESOLVED from `unresolved_from` onward."""
    code = INDUSTRY_UNRESOLVED
    for eff, tse, unres in idx.get(sid, ()):
        if eff <= as_of:
            code = tse or INDUSTRY_UNRESOLVED
            if unres and unres <= as_of:
                code = INDUSTRY_UNRESOLVED
    return code


def _f(v):
    if v is None:
        return None
    try:
        x = float(v)
    except (TypeError, ValueError):
        return None
    return None if x != x or not math.isfinite(x) else x


# --- per-security precomputation ----------------------------------------------

class SecuritySeries:
    """Everything a period lookup needs, computed once over full history.

    Rolling quantities are computed here rather than per period because the
    frozen definitions are the same at every as-of: C-25's ADV20 is a mean over
    20 OBSERVED sessions, C-26's sigma20d is the SD of 20 log returns, and both
    are bounded by the current listing spell (O-G). Recomputing them 141 times
    would be the same arithmetic with 141 chances to drift.
    """

    __slots__ = ("sid", "dates", "pos", "close", "open_", "adj", "adv20",
                 "sigma20", "month_end", "spells", "unresolved")

    def __init__(self, sid, dates, close, open_, volume, factors,
                 unresolved_from, spells, sigma_at=()):
        self.sid = sid
        self.dates = dates
        self.pos = {d: i for i, d in enumerate(dates)}
        self.close = close
        self.open_ = open_
        self.adj = adjusted_closes(dates, close, factors)
        self.unresolved = tuple(unresolved_from or ())
        self.spells = spells

        turnover = close * volume
        self.adv20 = _rolling_mean(turnover, ADV_SESSIONS)
        self.sigma20 = _rolling_sigma(self.adj, SIGMA_SESSIONS, sigma_at)

        # last observed session of each calendar month
        me = {}
        for i, d in enumerate(dates):
            me[d[:7]] = i
        self.month_end = me

    def unresolved_at(self, as_of):
        """C-50/R8 bounded by as_of: the latest broken boundary already in force."""
        i = bisect.bisect_right(self.unresolved, as_of) - 1
        return self.unresolved[i] if i >= 0 else None

    def spell_start(self, as_of):
        i = bisect.bisect_right(self.spells, as_of) - 1
        return self.spells[i] if i >= 0 else None


def _rolling_mean(values, n):
    out = np.full(len(values), np.nan)
    if len(values) >= n:
        c = np.cumsum(np.insert(values, 0, 0.0))
        out[n - 1:] = (c[n:] - c[:-n]) / n
    return out


def _rolling_sigma(adj, n, at):
    """C-26 sigma20d, evaluated at the sessions a decision actually stands on.

    `compute_sigma20d` is called rather than reimplemented — a second SD in the
    materializer is exactly the kind of quiet divergence M-1 exists to stop —
    but only at the 141 as-of positions, because the other 5.8M evaluations
    would be arithmetic nobody reads.
    """
    out = np.full(len(adj), np.nan)
    for i in at:
        if i >= n:
            v = compute_sigma20d(list(adj[i - n:i + 1]))
            out[i] = np.nan if v is None else v
    return out


def build_series(px, cal, factors, unresolved, status_idx, as_ofs=()):
    calpos = {d: i for i, d in enumerate(cal)}
    out = {}
    for sid, g in px.groupby("stock_id", sort=True):
        dates = g["date"].tolist()
        close = g["close"].to_numpy(dtype=float)
        open_ = g["open"].to_numpy(dtype=float)
        vol = g["volume_shares"].to_numpy(dtype=float)
        first, last = dates[0], dates[-1]
        expected = cal[calpos[first]: calpos[last] + 1] if first in calpos else dates
        priced = set(dates)

        def explained(s_first, _sid=sid):
            return known_status_at(status_idx, _sid, s_first) != "listed"

        spells = spell_starts(expected, priced,
                              lambda s_first: explained(s_first)) or [dates[0]]
        pos = {d: i for i, d in enumerate(dates)}
        sigma_at = [pos[a] for a in as_ofs if a in pos]
        out[sid] = SecuritySeries(sid, dates, close, open_, vol,
                                  factors.get(sid, ()), unresolved.get(sid, ()),
                                  spells, sigma_at)
    return out


# --- per-period assembly -------------------------------------------------------

# 4.1a. Depths are DERIVED from the frozen members, never restated here. The
# first sealed run rejected 100% of the universe in every period because this
# file said 13 where `revenue_accel` needs 18, and nothing compared the two.
from core.b0_features import series_requirements       # noqa: E402

_REQ = series_requirements()
QUARTERS = max(8, _REQ["eps_by_quarter"])   # supplied depth may exceed the need
MONTHS_REVENUE = _REQ["monthly_revenue"]    # 18, set by revenue_accel
MONTH_ENDS_REQUIRED = _REQ["month_end_prices"]   # 14, zero margin, intentional


def _quarter_series(rows, as_of, field):
    """The last QUARTERS values of `field`, CALENDAR-QUARTER indexed (4.1a-R2).

    Published on or before as_of (2.2), then laid out on consecutive fiscal
    quarters with an explicit None for any quarter that has no published figure.
    Compressing the gap out is what makes `series[-5]` stop being four quarters
    before `series[-1]`: measured at period 1, 177 of 1,730 securities (10.23%)
    had a non-contiguous last-8, so eps_growth compared the wrong base period and
    the TTM sums spanned five calendar quarters for every one of them.
    """
    seen = {}
    for r in rows:
        if r.release_date > as_of:
            continue
        seen[pd.Period(r.date, freq="Q")] = getattr(r, field)
    if not seen:
        return ()
    last = max(seen)
    span = pd.period_range(end=last, periods=QUARTERS, freq="Q")
    return tuple(_f(seen.get(q)) for q in span)


def _latest_quarter_row(rows, as_of):
    best = None
    for r in rows:
        if r.release_date <= as_of and (best is None or (r.date, r.release_date) >
                                        (best.date, best.release_date)):
            best = r
    return best


def _monthly_revenue(rows, as_of):
    """MONTHS_REVENUE values, CALENDAR-MONTH indexed (4.1a-R2).

    `compute_revenue_yoy` reads `series[-1]` against `series[-13]`, so t-12 is
    only truly last year's same month if the index is consecutive months. Current
    measured impact of compressing is 0 of 1,647 securities - this is an
    invariant, not a correction, and it is cheapest to impose now.
    """
    seen = {}
    for rel, d, rev in rows:
        if rel <= as_of:
            seen[pd.Period(d[:7], freq="M")] = rev
    if not seen:
        return []
    last = max(seen)
    span = pd.period_range(end=last, periods=MONTHS_REVENUE, freq="M")
    return [_f(seen.get(m)) for m in span]


def _month_end_prices(ss, as_of, spell, unresolved):
    """14 month-end ADJUSTED closes, newest last. NA where the unit basis breaks."""
    months = pd.period_range(end=pd.Period(as_of[:7], freq="M"),
                             periods=MONTH_ENDS_REQUIRED, freq="M")
    out = []
    for m in months:
        key = str(m)
        i = ss.month_end.get(key)
        if i is None or ss.dates[i] > as_of:
            # the current month is bounded by as_of, not by its calendar end
            cand = [j for j, d in enumerate(ss.dates) if d[:7] == key and d <= as_of]
            i = cand[-1] if cand else None
        if i is None:
            out.append(None)
            continue
        d = ss.dates[i]
        if spell is not None and d < spell:
            out.append(None)              # O-G: a window may not cross a spell
        elif unresolved is not None and d < unresolved:
            out.append(None)              # C-50/R8: no comparable unit basis
        else:
            out.append(_f(ss.adj[i]))
    return out


def build_period(p, series, fin_idx, rev_idx, ind_idx, val_by_month,
                 status_idx, ca_by_sid, cal):
    as_of, exec_date = p["as_of"], p["execution_date"]
    window_start = str(pd.Period(as_of[:7], freq="M")
                       - (MONTH_ENDS_REQUIRED - 1))
    val = val_by_month.get(p["decision_month"], {})
    rows = []
    for sid, ss in series.items():
        i = ss.pos.get(as_of)
        if i is None:
            continue                       # not quoted at the decision point
        spell = ss.spell_start(as_of)
        if spell is None:
            continue
        si = ss.pos[spell]
        n_in_spell = i - si + 1
        unres = ss.unresolved_at(as_of)
        adv = ss.adv20[i]
        if n_in_spell < ADV_SESSIONS or not np.isfinite(adv):
            # NA is for a dependency that is genuinely unavailable: fewer than
            # the required observed sessions in this spell (O-G resets ADV20 at
            # the spell start), or a non-finite input.
            adv = None
        # B0.5 · R1/R2. An ADV20 of exactly 0 is NOT encoded as absence any more.
        # Twenty observed zero-volume sessions average to 0.0, which is a
        # liquidity OBSERVATION. The previous code dropped it, reasoning that
        # 4.2's floor rejects 0 anyway so the encoding "changes no eligibility
        # outcome" -- but 4.2 aborts on a MISSING adv20 before it ever reaches
        # the floor, which is exactly how B04DIAG-d5f34a5164a0e309 stopped on a
        # name quoted all year at a frozen price with no turnover.
        sig = ss.sigma20[i]
        if n_in_spell < SIGMA_SESSIONS + 1 or not np.isfinite(sig):
            sig = None
        elif unres is not None and ss.dates[max(0, i - SIGMA_SESSIONS)] < unres:
            sig = None                     # C-50/R8 reaches into the sigma window
        _status = known_status_tuple_at(status_idx, sid, as_of)
        j = ss.pos.get(exec_date)
        v = val.get(sid, {})
        frows = fin_idx.get(sid, ())
        latest = _latest_quarter_row(frows, as_of)
        mrev = _monthly_revenue(rev_idx.get(sid, ()), as_of)
        rows.append({
            "stock_id": sid,
            "mark": _f(ss.close[i]),
            "adv20": _f(adv),
            "sigma20d": _f(sig),
            "execution_open": _f(ss.open_[j]) if j is not None else None,
            "spell_start": spell,
            "known_status": _status[0],
            "status_available_from": _status[1],
            "status_effective_from": _status[2],
            "month_end_prices": _month_end_prices(ss, as_of, spell, unres),
            "monthly_revenue": [_f(x) for x in mrev],
            "net_income_by_quarter": list(_quarter_series(frows, as_of, "net_income")),
            "revenue_by_quarter": list(_quarter_series(frows, as_of, "revenue")),
            "gross_profit_by_quarter": list(_quarter_series(frows, as_of, "gross_profit")),
            "eps_by_quarter": list(_quarter_series(frows, as_of, "eps")),
            "period_end_equity": _f(getattr(latest, "equity", None)),
            "total_liabilities": _f(getattr(latest, "total_liabilities", None)),
            "total_assets": _f(getattr(latest, "total_assets", None)),
            "current_assets": _f(getattr(latest, "current_assets", None)),
            "current_liabilities": _f(getattr(latest, "current_liabilities", None)),
            "per_tse": _f(v.get("per_tse")),
            "pbr_tse": _f(v.get("pbr_tse")),
            "pit_industry": industry_at(ind_idx, sid, as_of),
            "corporate_action_events": [
                [e["kind"], e["ex_or_effective_date"], e["reconstructibility"]]
                for e in ca_by_sid.get(sid, ())
                if window_start <= e["ex_or_effective_date"] <= as_of],
        })
    return rows


# --- the hashed view -----------------------------------------------------------

def market_state_payload(p, rows):
    """The market side of `CanonicalDecisionInput.state_payload`, and only that.

    Deliberately absent: cash, shares, pending_exit, receivables and exposures.
    Definition B — those are causally generated by executing the previous period,
    so a market-side hash that included a placeholder for them would be a hash of
    a fabrication. `assert_market_state_is_portfolio_free` pins that.
    """
    return {
        "decision_month": p["decision_month"],
        "decision_date": p["decision_date"],
        "as_of": p["as_of"],
        "execution_date": p["execution_date"],
        "marks": {r["stock_id"]: r["mark"] for r in rows
                  if r["mark"] is not None and r["mark"] > 0},
        "adv20": {r["stock_id"]: r["adv20"] for r in rows if r["adv20"] is not None},
        "sigma20d": {r["stock_id"]: r["sigma20d"] for r in rows
                     if r["sigma20d"] is not None},
        "execution_prices": {r["stock_id"]: r["execution_open"] for r in rows
                             if r["execution_open"] is not None},
        "untradable": sorted(r["stock_id"] for r in rows
                             if r["known_status"] != "listed"),
        # B0.6. `build_input` now feeds the PIT status dates into the decision,
        # so they are decision inputs and the hashed view must bind them.
        # Leaving them out would let two states with different status dates hash
        # identically -- the same sealed-input sufficiency defect (C-55) this
        # repair exists to close, one field further down.
        #
        # Only non-listed rows carry information here: a listed row's dates are
        # consulted by no rule, and any listed/non-listed flip already moves
        # `untradable` above.
        "security_status": [
            {"stock_id": r["stock_id"], "known_status": r["known_status"],
             "status_available_from": r["status_available_from"],
             "status_effective_from": r["status_effective_from"]}
            for r in sorted(rows, key=lambda x: x["stock_id"])
            if r["known_status"] != "listed"],
        "listing_spells": [{"stock_id": r["stock_id"], "start": r["spell_start"]}
                           for r in sorted(rows, key=lambda x: x["stock_id"])],
        "pit_inputs": [
            {"stock_id": r["stock_id"],
             "net_income_by_quarter": r["net_income_by_quarter"],
             "revenue_by_quarter": r["revenue_by_quarter"],
             "gross_profit_by_quarter": r["gross_profit_by_quarter"],
             "eps_by_quarter": r["eps_by_quarter"],
             "period_end_equity": r["period_end_equity"],
             "total_liabilities": r["total_liabilities"],
             "total_assets": r["total_assets"],
             "current_assets": r["current_assets"],
             "current_liabilities": r["current_liabilities"],
             "monthly_revenue": r["monthly_revenue"],
             "month_end_prices": r["month_end_prices"],
             "per_tse": r["per_tse"],
             "pbr_tse": r["pbr_tse"],
             "pit_industry": r["pit_industry"]}
            for r in sorted(rows, key=lambda x: x["stock_id"])],
        "corporate_action_events": [
            {"stock_id": r["stock_id"], "events": r["corporate_action_events"]}
            for r in sorted(rows, key=lambda x: x["stock_id"])
            if r["corporate_action_events"]],
    }


LIST_COLUMNS = ("month_end_prices", "monthly_revenue", "net_income_by_quarter",
                "revenue_by_quarter", "gross_profit_by_quarter",
                "eps_by_quarter", "corporate_action_events")
SCALAR_COLUMNS = ("mark", "adv20", "sigma20d", "execution_open", "per_tse",
                  "pbr_tse", "period_end_equity", "total_liabilities",
                  "total_assets", "current_assets", "current_liabilities")


def rows_from_parquet(df):
    """The exact inverse of what `main` writes.

    Parquet round-trips a Python list of floats as a numpy array and `None` as
    NaN, so a naive read-back hashes differently from what was hashed. This is
    the ONE place that knows the round-trip, used by the rebuild check as well,
    so "it rebuilds identically" is a property of the artefact rather than of
    whoever wrote the reader.
    """
    rows = df.to_dict("records")
    for r in rows:
        r["stock_id"] = str(r["stock_id"])
        for k in LIST_COLUMNS:
            v = r[k]
            if v is None:
                r[k] = []
            elif k == "corporate_action_events":
                r[k] = [[str(x) for x in list(e)] for e in list(v)]
            else:
                r[k] = [_f(x) for x in list(v)]
        for k in SCALAR_COLUMNS:
            r[k] = _f(r[k])
        for k in ("spell_start", "known_status", "status_available_from",
                  "status_effective_from", "pit_industry"):
            r[k] = str(r[k])
    return rows


PORTFOLIO_FIELDS = ("cash", "shares", "pending_exit", "cash_dividend_receivable",
                    "stock_dividend_receivable", "exposures", "portfolio")


def assert_market_state_is_portfolio_free(payload):
    """Definition B, as a check rather than a comment."""
    leaked = [k for k in PORTFOLIO_FIELDS if k in payload]
    if leaked:
        raise SystemExit(
            "definition B: the market-side state carries portfolio fields %s. "
            "portfolio[t] is causally generated by executing t-1 and may not be "
            "invented here." % leaked)


def main() -> int:
    assert_not_writing_into_frozen_b0(OUTDIR)
    assert_not_writing_into_frozen_b0(MANIFEST)
    _log("lineage: %s  window %s .. %s (%d periods)"
         % (LINEAGE, WINDOW_START, WINDOW_END, WINDOW_MONTHS))
    os.makedirs(OUTDIR, exist_ok=True)
    _log("loading sealed sources ...")
    cal, px, ledger, status, bonus, val, fin, rev, ind = load_sources()
    periods = decision_periods(cal)
    _log("periods: %d  %s .. %s" % (len(periods), periods[0]["decision_month"],
                                    periods[-1]["decision_month"]))

    factors, unresolved, adj_stats = adjustment_plan(ledger, bonus, cal)
    _log("share-unit factors: %s" % dict(adj_stats))
    _log("securities with an unresolved eligible boundary: %d" % len(unresolved))

    status_idx = status_index(status)
    _log("deriving listing spells and rolling windows ...")
    series = build_series(px, cal, factors, unresolved, status_idx,
                          [p["as_of"] for p in periods])
    _log("securities with a price history: %d" % len(series))

    fin_idx = financial_index(fin)
    rev_idx = revenue_index(rev)
    ind_idx = industry_index(ind)
    val_by_month = {}
    for r in val.itertuples():
        val_by_month.setdefault(str(r.decision_month), {})[str(r.stock_id)] = {
            "per_tse": r.per_tse, "pbr_tse": r.pbr_tse}
    ca_by_sid = collections.defaultdict(list)
    for row in ledger:
        ca_by_sid[str(row["stock_id"])].append(row)

    manifest, built = [], 0
    for p in periods:
        rows = build_period(p, series, fin_idx, rev_idx, ind_idx, val_by_month,
                            status_idx, ca_by_sid, cal)
        if not rows:
            raise SystemExit("period %s produced no market-side state"
                             % p["decision_month"])
        payload = market_state_payload(p, rows)
        assert_market_state_is_portfolio_free(payload)
        sha = canonical_sha256(payload)
        out = os.path.join(OUTDIR, "%s.parquet" % p["decision_month"])
        assert_not_writing_into_frozen_b0(out)
        pd.DataFrame(rows).to_parquet(out, index=False)
        manifest.append({
            "decision_month": p["decision_month"],
            "decision_date": p["decision_date"],
            "as_of": p["as_of"],
            "execution_date": p["execution_date"],
            "securities": len(rows),
            "marks": len(payload["marks"]),
            "adv20": len(payload["adv20"]),
            "sigma20d": len(payload["sigma20d"]),
            "execution_prices": len(payload["execution_prices"]),
            "untradable": len(payload["untradable"]),
            "market_state_sha256": sha,
            "artefact": os.path.relpath(out, REPO).replace("\\", "/"),
        })
        built += 1
        if built % 20 == 0:
            _log("  built %d/%d  (%s: %d securities)"
                 % (built, len(periods), p["decision_month"], len(rows)))

    with open(MANIFEST, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(manifest, fh, ensure_ascii=False, indent=1)

    composed = "".join("%s:%s\n" % (m["decision_month"], m["market_state_sha256"])
                       for m in manifest)
    import hashlib
    composed_sha = hashlib.sha256(composed.encode()).hexdigest()
    receipt = {
        "lineage": LINEAGE,
        "artefact": os.path.relpath(OUTDIR, REPO).replace("\\", "/")
                    + "/<decision_month>.parquet",
        "manifest": os.path.relpath(MANIFEST, REPO).replace("\\", "/"),
        "builder": "research/b0_materializer/build_market_side_state.py",
        "clause": "definition A · %d market-side canonical states, pre-L2"
                  % WINDOW_MONTHS,
        "periods_built": built,
        "periods_required": WINDOW_MONTHS,
        "window": [WINDOW_START, WINDOW_END],
        "composed_market_state_sha256": composed_sha,
        "securities_min": min(m["securities"] for m in manifest),
        "securities_max": max(m["securities"] for m in manifest),
        "share_unit_adjustment": dict(adj_stats),
        "securities_with_unresolved_boundary": len(unresolved),
        "portfolio_side_materialized": False,
        "decision_layer_invoked": False,
        "performance_computed": False,
    }
    with open(RECEIPT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(receipt, fh, ensure_ascii=False, indent=1, sort_keys=True)

    _log("")
    _log("periods built            : %d/%d" % (built, WINDOW_MONTHS))
    _log("securities per period    : %d .. %d" % (receipt["securities_min"],
                                                  receipt["securities_max"]))
    _log("composed market-state sha: %s" % composed_sha)
    _log("wrote %s and %s" % (os.path.relpath(MANIFEST, REPO),
                              os.path.relpath(RECEIPT, REPO)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
