# -*- coding: utf-8 -*-
"""Definition B · the ONE full `CanonicalDecisionInput` that exists pre-L2.

`portfolio[t]` is causally generated by executing t-1, so `full_input[t]` cannot
exist before t-1 has run. Exactly one period escapes that: period 1, whose
portfolio is not an execution output but the frozen opening state — B0 starts the
window holding nothing but `C_ref` in cash, read from the registry rather than
produced by running anything.

This builder therefore constructs period 1's full input and NOTHING ELSE. It
does not run the decision layer, and `build_period_t_full_input` exists only to
fail loudly for every t > 1, which is the property definition B actually asks to
be demonstrated.

ONE recorded seam. The frozen opening state is declared at `window_start`
(2014-07-31, the decision date), while §6.6 dates the canonical decision state at
`resolve_as_of(window_start)` = 2014-07-30. With no holdings the two describe the
same economic state, but they are not the same hashed object, and this builder
re-dates nothing silently: it records both and reports the divergence.

    python research/b0_materializer/build_period1_full_input.py
"""
from __future__ import annotations

import csv
import json
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, REPO)
sys.path.insert(0, HERE)

from core.b0_canonical_hash import canonical_sha256, file_sha256   # noqa: E402
from core.b0_features import SecurityPitInputs                # noqa: E402
from core.b0_listing_spell import ListingSpell                # noqa: E402
from core.b0_market_state import SourceContract, TradingCalendar   # noqa: E402
from core.b0_master_prereg import spec                        # noqa: E402
from core.b0_route import resolve_as_of                       # noqa: E402
from core.b0_state import PortfolioState, SourceAttestation   # noqa: E402
from core.b0_adapter_retrospective import (                   # noqa: E402
    RetrospectiveSources, build_input,
)
from core.b0_price_universe import PriceSourceContract        # noqa: E402

DATA = os.path.join(REPO, "data", "b0")
MANIFEST = os.path.join(DATA, "market_state_manifest.json")
RECEIPT = os.path.join(HERE, "period1_full_input_receipt.json")


class PortfolioNotYetGenerated(RuntimeError):
    """Definition B: full_input[t] cannot exist before executing t-1."""


def opening_portfolio(as_of: str) -> PortfolioState:
    """The frozen opening state. Read from the registry, never invented."""
    return PortfolioState(as_of=as_of, cash=float(spec("C_ref")), shares={},
                          pending_exit={}, cash_dividend_receivable=0.0,
                          stock_dividend_receivable={})


def build_period_t_full_input(t: int, *, prior_execution_output=None):
    """Definition B, as an executable statement rather than a comment."""
    if t == 1:
        return build_period_1_full_input()
    if prior_execution_output is None:
        raise PortfolioNotYetGenerated(
            "definition B: full_input[%d] needs portfolio[%d], which is causally "
            "generated by executing period %d. It may not be fabricated, "
            "defaulted to an empty portfolio, or substituted with period %d's "
            "TARGET. The 140 remaining full inputs are intentionally deferred."
            % (t, t, t - 1, t - 1))
    raise PortfolioNotYetGenerated(
        "definition B: executing a prior period is L2. This builder is pre-L2 "
        "and does not run the decision layer.")


def _price_contract(receipt):
    """D1-6: the panel names the corpus it read; this reshapes, never invents."""
    src = receipt["price_source"]
    return PriceSourceContract(
        name=src["name"], importer_version=src["importer_version"],
        content_sha256=src["content_sha256"],
        schema_sha256=receipt["schema_sha256"],
        date_min=receipt["date_min"], date_max=receipt["date_max"],
        securities=receipt["securities"],
        includes_delisted=src["includes_delisted"],
        audit_sha256=receipt["content_sha256"],
        lineage=src["lineage"])


def _rows(month):
    return pd.read_parquet(os.path.join(DATA, "market_state", "%s.parquet" % month))


def _clean(seq):
    """Parquet round-trips a list of `None` as NaN; the core needs None back."""
    out = []
    for x in (seq if seq is not None else ()):
        out.append(None if x is None or (isinstance(x, float) and x != x)
                   else float(x))
    return tuple(out)


def _scalar(x):
    return None if x is None or (isinstance(x, float) and x != x) else float(x)


def build_period_1_full_input():
    with open(MANIFEST, encoding="utf-8") as fh:
        manifest = json.load(fh)
    p = manifest[0]
    sessions = tuple(r["session"] for r in csv.DictReader(
        open(os.path.join(DATA, "trading_calendar.csv"), encoding="utf-8")))
    calendar = TradingCalendar(
        sessions=sessions,
        source=SourceContract(
            name="b0_trading_calendar", kind="trading_calendar",
            importer_version="b0_calendar_importer@1",
            content_sha256=file_sha256(
                os.path.join(DATA, "trading_calendar.csv")),
            schema_sha256=canonical_sha256(["session"]),
            date_min=sessions[0], date_max=sessions[-1],
            has_effective_dates=True, has_availability_semantics=True,
            is_current_snapshot=False,
            availability_convention="session_close"))
    as_of = resolve_as_of(p["decision_date"], calendar)
    if as_of != p["as_of"]:
        raise SystemExit("§6.6 disagreement: manifest %s, route %s"
                         % (p["as_of"], as_of))

    df = _rows(p["decision_month"])
    marks, adv20, sigma20d, exec_px, untradable = {}, {}, {}, {}, set()
    pit_inputs, spells = [], []
    for r in df.itertuples():
        sid = str(r.stock_id)
        if _scalar(r.mark) is not None:
            marks[sid] = _scalar(r.mark)
        if _scalar(r.adv20) is not None:
            adv20[sid] = _scalar(r.adv20)
        if _scalar(r.sigma20d) is not None:
            sigma20d[sid] = _scalar(r.sigma20d)
        if _scalar(r.execution_open) is not None:
            exec_px[sid] = _scalar(r.execution_open)
        if r.known_status != "listed":
            untradable.add(sid)
        spells.append(ListingSpell(stock_id=sid, start=str(r.spell_start),
                                   opened_by="first_observation", as_of=as_of))
        pit_inputs.append(SecurityPitInputs(
            stock_id=sid,
            net_income_by_quarter=_clean(r.net_income_by_quarter),
            revenue_by_quarter=_clean(r.revenue_by_quarter),
            gross_profit_by_quarter=_clean(r.gross_profit_by_quarter),
            eps_by_quarter=_clean(r.eps_by_quarter),
            period_end_equity=_scalar(r.period_end_equity),
            total_liabilities=_scalar(r.total_liabilities),
            total_assets=_scalar(r.total_assets),
            current_assets=_scalar(r.current_assets),
            current_liabilities=_scalar(r.current_liabilities),
            monthly_revenue=_clean(r.monthly_revenue),
            month_end_prices=_clean(r.month_end_prices),
            per_tse=_scalar(r.per_tse),
            pbr_tse=_scalar(r.pbr_tse),
            pit_industry=str(r.pit_industry)))

    freeze = json.load(open(os.path.join(
        REPO, "research", "b0_registry", "master_prereg_freeze.json"),
        encoding="utf-8"))
    attestation = SourceAttestation(
        dataset_id="b0_market_side_state_20260819",
        provenance_sha256=freeze["spec_sha256"],
        pit_guard_passed=True,
        universe_guard_passed=True,
        satisfied_blocking_requirements=("price_universe_survivorship",),
        synthetic=False)
    price_receipt = json.load(open(os.path.join(HERE, "price_panel_receipt.json"),
                                   encoding="utf-8"))
    sources = RetrospectiveSources(
        calendar=calendar, status_table=None, attestation=attestation,
        marks=marks, adv20=adv20, sigma20d=sigma20d,
        pit_inputs=pit_inputs, price_observations=(),
        corporate_action_events=(), exposures=(),
        price_source=_price_contract(price_receipt),
        listing_spells=tuple(spells))
    portfolio = opening_portfolio(as_of)
    return build_input(sources, portfolio, p["decision_date"],
                       p["execution_date"], exec_px, frozenset(untradable))


def main() -> int:
    inp = build_period_1_full_input()
    payload = inp.state_payload()
    full_sha = canonical_sha256(payload)

    market_only = {k: v for k, v in payload.items()
                   if k not in ("cash", "shares", "pending_exit",
                                "cash_dividend_receivable",
                                "stock_dividend_receivable", "exposures")}
    frozen_opening = {
        "as_of": spec("window_start"), "cash": spec("C_ref"), "shares": {},
        "pending_exit": {}, "cash_dividend_receivable": 0.0,
        "stock_dividend_receivable": {}}

    try:
        build_period_t_full_input(2)
        raise SystemExit("definition B: period 2 built without period 1 output")
    except PortfolioNotYetGenerated as exc:
        deferred_reason = str(exc)

    receipt = {
        "artefact": "period 1 full CanonicalDecisionInput (in memory, pre-L2)",
        "builder": "research/b0_materializer/build_period1_full_input.py",
        "decision_date": inp.decision_date,
        "as_of": inp.as_of,
        "execution_date": inp.execution_date,
        "securities_with_marks": len(inp.snapshot.marks),
        "pit_inputs": len(inp.pit_inputs),
        "listing_spells": len(inp.listing_spells),
        "untradable": len(inp.untradable),
        "full_decision_input_sha256": full_sha,
        "market_side_only_sha256": canonical_sha256(market_only),
        "portfolio": {"cash": inp.portfolio.cash,
                      "shares": dict(inp.portfolio.shares),
                      "as_of": inp.portfolio.as_of},
        "opening_state_seam": {
            "frozen_opening_state_as_of": spec("window_start"),
            "canonical_decision_state_as_of": inp.as_of,
            "note": ("the registry declares the opening state at window_start "
                     "while §6.6 dates the canonical decision state at the prior "
                     "completed session; with no holdings the two describe the "
                     "same economic state but hash differently"),
            "frozen_opening_sha256": canonical_sha256(frozen_opening),
            "as_dated_opening_sha256": canonical_sha256(
                {**frozen_opening, "as_of": inp.as_of}),
        },
        "periods_with_full_input": 1,
        "periods_deferred": 140,
        "deferral_reason": deferred_reason,
        "decision_layer_invoked": False,
        "performance_computed": False,
    }
    with open(RECEIPT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(receipt, fh, ensure_ascii=False, indent=1, sort_keys=True)
    for k in ("decision_date", "as_of", "execution_date", "securities_with_marks",
              "pit_inputs", "untradable", "full_decision_input_sha256",
              "market_side_only_sha256"):
        print("%-26s %s" % (k, receipt[k]))
    print("wrote", os.path.relpath(RECEIPT, REPO))
    return 0


if __name__ == "__main__":
    sys.exit(main())
